#' @title Get F for Burn-in Period ???
#' @description 
#' 
#' @template global_stock
#' @param Rfun_BmsySim A list of functions for use in get_FBRP(), generated by processes/Rfun_BmsySim.R
#' @template global_yrs
#' @param temp ??? Used in growthSamplePopulation.R, waaByYear.R cohortGrowthPlots.R need to clarify if this is temperature or temporary file
#' @template global_yrs_temp
#' @template global_y
#' 
#' @return 
#' 
#' @family setup
#' 

get_burnF <- function(stock,
                      Rfun_BmsySim,
                      yrs, # managmeent years
                      temp,
                      yrs_temp, # temperature years
                      y){

  Rfun_lst <- Rfun_BmsySim
  parmgt <- list(RFUN_NM = 'forecast', #??? Should these be function arguments rather than fixed?
                 FREF_TYP = 'FmsySim',
                 FREF_PAR0 = length(yrs)-1)
 
  parenv <- list(tempY = temp,
                 Tanom = rep(0,length(yrs)),
                 yrs = yrs, # management years
                 yrs_temp = yrs_temp, # temperature years
                 y = 1)
  
  parpop <- with(stock, {
                   list(
                     waa = waa[1,, drop=FALSE], # ??? Confirm that these are objects within stock
                     sel = slxC[1,, drop=FALSE], 
                     M = init_M, 
                     mat = mat[1,, drop=FALSE],
                     R = NA,
                     SSBhat = SSB[1, drop=FALSE],
                     J1N = J1N[1,, drop=FALSE],
                     Rpar = Rpar,
                     Fhat = NA,
                     switch= TRUE)})

  Fref <- get_FBRP(parmgt = parmgt, parpop = parpop, parenv = parenv, 
                   Rfun_lst = Rfun_lst, stockEnv=stock)
  
  return(Fref$RPvalue)
}





