#' @title Get Replacement, improve title/description
#' @description 
#' 
#' @inheritParams get_FBRP
#' @param plot A boolean, if TRUE plots generated
#' @param Rfun_BmsySim A list of functions, generated by processes/Rfun_BmsySim.R ??? probably worth standardizing (Rfun_BmsySim here Rfun_lst in get_FBRP) so documentation can be inherited
#'
#' @return A number for the median ratio for R/SSBhat (slp)
#' 
#' @family managementProcedure, regulations
#' 

get_replacement <- function(parpop, 
                            parmgt, 
                            plot=FALSE,
                            Rfun_BmsySim){
  
  ###### ----- must change L5SAMP here..... --------#######
  # Change setup here it is ridiculous.
  Rfun <- Rfun_BmsySim[[parmgt$RFUN_NM]]
  if(parmgt$RFUN_NM == 'L5SAMP'){
    parpop$B <- tail(parpop$SSBhat, 5)
    parpop$R <- tail(parpop$R, 5)
  }

  # model to approximately bisect the S/R data (goes through origin)
  bimod <- lm(parpop$R ~ 0 + parpop$SSBhat)

  # slp of the bisecting line
  # slp <- coef(bimod)
  slp <- median(parpop$R / parpop$SSBhat)
  
  if(plot){
    xl <- c(0, max(parpop$SSBhat))
    yl <- c(0, max(parpop$R))
    plot(parpop$R ~ parpop$SSBhat, xlim=xl, ylim=yl, main=slp)
    abline(a=0, b=slp)
  }
  
  return(unname(slp))
}
