---
title: "Implementation Error"
author: Min-Yang Lee , Anna Birkenbach, Truesdell, Cummings, Kerr, TBD
abstract: |
 To be reasonably accurate, a multispecies simulation model must account for techincal interactions. We do that for the northeast US groundfish fishery.  This allows for fishing mortality to be systematically different from the level set by fishery managers.
keywords:
  - Management Strategy Evaulation 
  - Integrated Bioeconomic Models 
  - Fisheries
link-citations: yes
header-includes:
- \usepackage{graphicx}
- \usepackage{float}
- \usepackage{pdflscape}
- \usepackage{setspace}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
- \onehalfspacing
output: 
  bookdown::pdf_book:
    keep_tex: yes
    toc: False
    fig_caption: yes
bibliography: library.bib
---

<!---Don't read, or touch this part

author:  Lee, Birkenbach, 
output:
  pdf_document:
     base_format: rticles::oup_article
csl: canadian-journal-of-fisheries-and-aquatic-sciences.csl 
    keep_tex: yes
  html_document: null
  word_document: null
 
---


  -->
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(kableExtra)
library(tikzDevice)
#library(devtools)
#devtools::install_github("adletaw/captioner")
library(captioner)
here::i_am("documentation/economics/econ_documentation.Rmd")
library(here)
fig_nums <- captioner(prefix= "Figure")


```
<!---End of the don't read, or touch this part -->

Funding acknowledgements:

Intended Outlet: ICES-JMS, CJFAS, Frontiers in Marine Science

\newpage
```{r child = here("documentation","economics","sections","Executive_Summary.Rmd")}
```
\newpage
Intentionally Blank.
\newpage

# Introduction
```{r child = here("documentation","economics","sections","Introduction.Rmd")}
```
# Methods
```{r child = here("documentation","economics","sections","Methods.Rmd")}
```

# Results
```{r child = here("documentation","economics","sections","Results.Rmd")}
```

# Discussion
```{r child = here("documentation","economics","sections","Discussion.Rmd")}
```

# Acknowledgements

# References
<div id="refs"></div>

\newpage

# Tables

<!---markdown style table. fucking escape characters
```{r symboltable, tab.cap="Table of Symbols \\label{symtab}", echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
tabl <- "
|	Symbol	|	Definition
|:--------	|:--------------------------------------------------------
|	$y$	|	year
|	$a$	|	age
|	$\\varepsilon_{\\phi,y}$	|	assessment error
|	$\\bar{F}_y$	|	fishing mortality that would remove quota from herring population
|	$Q_y$	|	quota for herring fishery
|	$\\varepsilon_{\\theta,y}$	|	implementation error
|	$\\sigma_{\\theta}^2$	|	variance of implementation error
|	$GR_y$	|	gross revenue
|	$q_y$	|	quantity landed
"
cat(tabl) # output the table in a format good for HTML/PDF/docx conversion
```
-->

# Figures




