get_hydra <- function(manage_counter){
  #send hydra data to groundfish MSE?
  #Packages you need:
  #tidyr
  #here
  
  #This is the number of years the MSE has gone on, will inform Nyears
  MSEyr = manage_counter
  source(here("functions/hydra/get_hydra_data.R"))
  get_hydra_data(MSEyr)
  
  #for now load in data I already have for testing
  load(here("functions/hydra/hydraDataList_msk.rda")) # update R list annually
  
  
  #############################################################################
  #Start of Emily's code, it runs hydra and pulls data files:
  #Source the baseline hydra sim data:

  
  #Write a new hydra sim file, changing anything before this line
  fileConn<-file("functions/hydra/hydra_sim_data.dat")
  writeLines(as.character(c(debug, Nyrs, Nspecies, Nsizebins, Nareas, Nfleets, 
               Nsurveys, wtconv,datfilename,binwidth, lenwt_a, lenwt_b, 
               Nrecruitment_cov, Nmaturity_cov, Ngrowth_cov, 
               recruitment_cov, maturity_cov, growth_cov, obs_effort, 
               mean_stomwt, bs_temp,yr1Nphase, recphase, avg_rec_phase, 
               recsigmaphase, avg_F_phase, dev_rec_phase, dev_F_phase, 
               fqphase, fsphase, sqphase, ssphase, ssig_phase, sig_phase,
               m1_phase, oF1_phase, oFdev_phase, vuln_phase, 
               recGamma_alpha, recGamma_shape, recGamma_beta, 
               recDS_alpha, recDS_shape, recDS_beta, recGamSSB_alpha, 
               recGamSSB_shape, recGamSSB_beta, recRicker_alpha, 
               recRicker_shape, recRicker_beta, recBH_alpha, recBH_shape,
               recBH_beta, recShepherd_alpha, recShepherd_shape, 
               recShepherd_beta, recHockey_alpha, recHockey_shape, 
               recHockey_beta, recSegmented_alpha, recSegmented_shape, 
               recSegmented_beta, rectype, stochrec, sexratio, 
               recruitment_covwt, fecund_d, fecund_h, fecund_theta, 
               maturity_nu, maturity_omega, maturity_covwt, growth_psi, 
               growth_kappa, growth_covwt, vonB_LinF, vonB_k, growthtype,
               phimax, intake_alpha, intake_beta, isprey,
               preferred_wtratio, sd_sizepref, B0, Nguilds, guildMembers,
               fleetMembers, AssessmentPeriod, flagRamp, minExploitation,
               maxExploitation, minMaxExploitation, minMaxThreshold, 
               Nthresholds, threshold_preportion, exploitation_levels, 
               threshold_species, AssessmentOn, speciesDetection, 
               LFI_size, scaleInitialN, effortScaled, discard_Coef, 
               discardSurvival_Coef, predOrPrey, bandwidth_metric, 
               baseline_threshold, indicator_fishery_q, AR_parameters, 
               flagMSE, residentTime, areaMortality, eof)),fileConn)
  close(fileConn)
  
  # Random number to run the MSE
  randomnum <- 100
  # randomnum <- round(randu(1,100),1)

  # Set the working directory to where the hydra executable is
  originalwd <- getwd()
  setwd(paste0(originalwd,"/functions/hydra"))
  
  # Run the hydra code
  runmod <- paste("hydra_sim.exe -sim ",randomnum, "-ind hydra_sim_data.dat -ainp hydra_sim_GB_5bin_1978_inpN_m1oF.pin -nohess -maxfn 1")
  out <- system(runmod, intern=T)
  
  # Reset the working directory to original
  setwd(originalwd)
  
  #Read the report object generated by admb into R
  source("functions/hydra/read.report.R")
  hydra_sim_rep <- reptoRlist("functions/hydra/hydra_sim.rep")
  
  #Convert general report object into things to be fed back
  surveydata.df <- hydra_sim_rep$survey
  colnames(surveydata.df) <- c("survey","year","species","biomass","cv","predbiomass","residual","NLL")
  catchdata.df <- hydra_sim_rep$catch
  colnames(catchdata.df) <- c("fishery","area","year","species","catch","cv","predcatch","residual","NLL")
  
  #End of Emily's code. Next step, replace subsequent code with items from hydra_sim_data and hydra_sim_rep
  #############################################################################
  
  #rearrange to look like data that we need
  species <- data.frame(name=speciesList, species= c(1:10))
  K <-as.numeric(vonB_k) 
  Linf <- as.numeric(vonB_LinF) 
  t0 <- 0 # is there something else I should be using here? t0 probably fine
  vonbert <- data.frame(species,K, Linf,t0)
  
  # size bins
  # binwidth <- hydraDataList_msk$binwidth%>%
  #   cbind(species)
  binwidth <- data.frame(sizebin1=matrix(binwidth,nrow=10,ncol=5,byrow=T)[,1],
                         sizebin2=matrix(binwidth,nrow=10,ncol=5,byrow=T)[,2],
                         sizebin3=matrix(binwidth,nrow=10,ncol=5,byrow=T)[,3],
                         sizebin4=matrix(binwidth,nrow=10,ncol=5,byrow=T)[,4],
                         sizebin5=matrix(binwidth,nrow=10,ncol=5,byrow=T)[,5],
                         name=speciesList,
                         species=guildMembers)
  row.names(binwidth) <- speciesList
  
  sizebin0 <- 0
  sizebin1 <- binwidth$sizebin1
  sizebin2 <- sizebin1 + binwidth$sizebin2 
  sizebin3 <- sizebin2 + binwidth$sizebin3
  sizebin4 <- sizebin3 + binwidth$sizebin4
  sizebin5 <- sizebin4 + binwidth$sizebin5
  sizebin <- as.data.frame(cbind(sizebin0,sizebin1, sizebin2, sizebin3, sizebin4, sizebin5, species))%>%
    full_join(vonbert)
  
  sizebins <- as.data.frame(cbind(sizebin0,sizebin1, sizebin2, sizebin3, sizebin4, sizebin5, species))%>%
    gather(bin, endbin, sizebin0:sizebin5)%>%
    group_by(species)%>%
    mutate(startbin= dplyr::lag(endbin))%>%
   dplyr::filter(!bin %in% c('sizebin0'))
  
  # Start here
  # calculate the number of fish in each bin- Problem this is not an integer
  observedSurvSize<- hydraDataList_msk$observedSurvSize
  SurvData <- gather(observedSurvSize, bin, prop, sizebin1:sizebin5)%>%
    mutate(N= ceiling(inpN*prop))%>% #fix by rounding?
    full_join(sizebins, by=c("species", "bin"))%>%
    full_join(vonbert)
  
  observedCatchSize <- hydraDataList_msk$observedCatchSize
  catchData <- gather(observedCatchSize, bin, prop, sizebin1:sizebin5)%>%
    mutate(N= ceiling(inpN*prop))%>% #fix by rounding?
    full_join(sizebins, by=c("species", "bin"))%>%
    full_join(vonbert)
  
  Surv_newbin<-SurvData%>%
    rowwise()%>%
    mutate(end = min(endbin, Linf-1), start= min(startbin, Linf-1)) #fix by choosing whichever is smallest?
  Catch_newbin <- catchData%>%
    rowwise()%>%
    mutate(end = min(endbin, Linf-1), start= min(startbin, Linf-1)) 
  
  #repeat rows based on N- each individual has its own row
  SurvRep <- as.data.frame(lapply(Surv_newbin, rep, Surv_newbin$N))
  CatchRep <- as.data.frame(lapply(Catch_newbin, rep, Catch_newbin$N))
  
  # some start bins are larger than Linf which will cause errors for calculating length
  # fixed this by forcing start to also be smaller than Linf
  # SurvCheck <- SurvRep%>%
  #   dplyr::filter(startbin>end)
  # CatchCheck <- CatchRep%>%
  #   dplyr::filter(startbin>end)
  # 
  # Survey <- anti_join(SurvRep,SurvCheck) # leave out problem lengths
  # Catch <- anti_join(CatchRep,CatchCheck)   
  
  # it seems like all of this is ultimately coming from the 
  hydraData <- list(observedSurSize=SurvRep,
                    observedCatchSize=CatchRep,
                    observedBiomass=surveydata.df[,1:5],
                    observedCatch=catchdata.df[,1:6])
  return(hydraData)
}