
Many of the complex simulation models used to inform fisheries managers take a phenomenological (reduced-form) approach [@Fenichel2013] to the process by which humans kill fish.
This relatively abstract representation of fishing fleets allow for intense focus on biological and ecosystem complexities. 
For example, @Wiedenmann2015,@Wiedenmann2017,@Ulrich2017,@Deroba2019, @Kritzer2019, and @Sun2019 assume the fishing mortality rate (F) is set directly by managers.
@punt2008evaluation, @Deroba2012Evaluating, @Li2018,@Hennen2018, @Thorpe2019b,@Deroba2019, @Siddeek2020, @Sun2021, @OFarrell2021, @Surma2021 assume that the actual fishing mortality rate is equal to the target fishing mortality rate modified by an idiosyncratic error term.
The distribution of this error term is approximated from historical data, although justification for the parameterization is typically scant.
@Holsman2020 takes a more sophisticated phenomenological approach by estimating a set of reduced form equations that explain aggregate total catch as a function of catch limits, catch limits of jointly caught stocks, and other parameters.
The drawback of the all phenomenological approaches to implementation error is that they suffer from the Lucas Critique [-@Lucas1976]: they will only be policy relevant to the extent that future conditions are similar to current conditions [@Fenichel2013].  
@Fulton2011a note that implementation error encompasses three distinct processes: (1) decisions where scientific advice on stock status is subordinated; (2) lack of direct regulatory control of fishing mortality due to inadequate enforcement or a lack of a direct link between controls (regulations) and harvest; and (3) unexpected behavioural responses of resource users.

Single species (or single stock) management is common in the US.
Fishery managers select F or an F-control rule at the stock level based on legal constraints and scientific advice; the fishing mortality rate is operationalized into an annual catch limit.
Legal constraints in the US include mandates to achieve Optimum Yield or rebuild overfished stocks of fish.
Scientific advice includes both estimates of current stock levels and future stock levels (that are functions of different levels of F).
This requires some assumptions about whether catch will be greater than, less than, or equal to the catch limit. 
When a stock of fish is not caught jointly with other stocks, the catch limits are "low" enough to matter, and the manager has enough information to effectively monitor and close the fishery when the catch limit is approached, the assumption that catch is equal to the catch limit, perhaps with some small error, is reasonable.
In the Northeast US, this situation might be true for Atlantic Herring and Atlantic Sea Scallops.

When the manager cannot acquire information to monitor in real-time, a fishing fleet's catch can be greater than it's catch limit. 
The recreational cod fishery in the Gulf of Maine is an example: catch is estimated using a survey and catch statistics are often not available until well after the end of the fishing year.
When two stocks of fish are caught jointly, the catch limit of one species may constrain a fishing fleet's catch of a second to be less than the catch limit.
The extent to which catch limits of one stock constrain catch of the other stock depends on stock conditions and catch limits of both stocks, technology used to capture those stocks, and the strength of the incentives to catch or avoid each stock.
When these factors change, the relationship between the constrained and constraining stocks are likely to change as well.
Finally, when catch limits are "high" catch will be less than the limit; this might occur if there is market power at some stage in the production process -- businesses may be able to deter entry of new vessels or lower catch in order to keep output prices high.
It may also occur if output prices are too low or input prices are too high to incentivize firms to enter or catch fish. 
These processes are difficult to model mechanistically and phenomenological approaches are often used to model F [@Fenichel2013; @Abbott2013]. 

We aim to address the second and third of these processes identified by @Fulton2011a (not the first) in the context of the Northeast United States multispecies fishery, commonly referred to as groundfish. 
Participants in this fishery target a collection of demersal fish in the Northwest Atlantic Ocean.  
Production is joint.  
We pair a mechanistic (structural) model of production in a multispecies fishery with stock dynamics and assessment models.
Our general approach is similar to that of @Ono2018.  
We focus on one specific way that technical interactions (or jointness in production) matter: the bycatch or "choke stock" story[^choke]  in multispecies fishery. [^diffs] 
We apply the model to the northeast US multispecies fishery, commonly referred to as groundfish.  
Participants in this fishery have been observed to change their  behavior in response to recent policy changes: @Scheld2018 and @Holzer2019 document changes in fishing behavior after changes in management.

[^choke]: we are not actually going to call this the "choke stock" story.

[^diffs]: We're doing something pretty different from @Ono2018.  Structural model instead of metier model. No "expansion factor" hacks for behavioral changes.  Fish stock model is fine.  



Another approach to implementation error is to model catch and effort phenomenologically.  
For example, the Fcube or FLBEIA derived models [@Garcia2021; @Garcia2017; @Prellozo2016;  @Ulrich2011] allow for sensitivity analysis into how the total effort of the fleet is partitioned metiers with different costs and catchability. 
Different rules for effort (fishing occurs until any quota is reached, a specific quota is reaches, or until all quotas are hit) and the allocation of effort across fleet segments (historical effort patterns or based on a "share" of value) can be investigated.
The FcubEcon model in @Hoff2010 allocates effort across metiers in a way that maximizes aggregate profits.
This provides a useful benchmark as it embeds the economic assumption of full and perfect markets.
A drawback is pointed out by @Weninger2019: these are analyst specified rules that are not grounded in models of human or firm behavior.
For example, a policy in which a catch limit is reduced by 90% for a constraining stock would simply see effort scaled down proportionally when simulated under the "when any quota is reached" rule.
Interesting behavioral adaptations that change either the types of effort or the way that effort is deployed are precluded.

When subsets of fishing vessels can be assumed homogeneous, the metier based approach [cf:@Merzereaud2011;@Guillen2014; @Ono2018] can be applied. 
The downside is ZZZZ.  
Metier based approaches often classify, in part, on outcome variables (catch composition, gear-area fished, etc.)

@Nielsen2018 review thirty-five integrated ecological-economic fisheries models: three (DISPLACE, IAM, and ELFSIM)  include models of individual fishing vessels, the rest use a metier or larger aggregation.  

DISPLACE includes a phenomenological model of vessel behavior at a very fine spatial and temporal scale [@Bastardie2010a]. @Bastardie2016 is an update.

> We demonstrate that integrating the spatial activity ofvessels and fish abundance dynamics allow for more realistic predictions of fishermen behaviour, profits, and stock abundance.

Basic ELFSIM -- The (base) model is at the metier, but this has been updated with a quota market model [@Little2007; @Little2009].  Two species, vessels assumed will stop fishing if it runs out of coral trout quota. 

IAM is listed as individual based, but that does not appear to be the case in Nephrops, Main documentation (@Merzereaud2011), or biscay sole @Guillen2013a.    @Bellanger2017 contains a large IAM improvement; however, there are no "choke stocks", which is very reasonable based on historical outcomes as long as the evaluated policies are "local."  <!-- Given @Belanger2017, and the quota market model in @Little2009, we'll have to thread the needle carefully with pitching the improvement of paper -->.

@Weninger2019 describes some shortcomings from EwE, Atlantis, FishRent, FCube, Temas, and DISPLACE as:

> In sum, two key commonalities arise in fishery sector models: (1) restrictive assumptions for the structure of the multiple-species harvest technology in the form of fixed output proportions and (2) use of user-specified and ad hoc rules to characterize fishing behavior which are commonly estimated by naive prediction, i.e., next period behavior will be equal to last period behavior. I next argue that robust prediction of commercial fishing outcomes in complex and decentralized fishery environments requires less restrictive assumptions for multiple-species harvesting technologies and adoption of rational decision rules that are consistent with regulatory instruments used to manage real world fisheries

@Ono2018 states:

>Some MSE frameworks include some elements of fleet dynamics (e.g., Atlantis (Fulton et al. 2011), BIOMAS (Ives et al. 2013), FLR (Kell et al. 2007), and ISIS-FISH (Pelletier et al. 2009)), but a multi- species fishery quota allocation model with trade-offs and con- straints (i.e., based on constrained optimization) as well as the temporal dynamics of technical interactions has never been included in an MSE.

Single species models, with or without random implementation error, cannot credibly model interrelated fisheries with technical interactions. 

We realistically allow for leakages out of the main fishery into other fisheries [@Cunningham2016].  Because our model is grounded in a structural model of individuals's utility maximization, instead of a reduced form model of metiers, we are better able to predict changes in behavior that result from changes in policies.  <!---For example, we can examine policies that include tradable output controls (ITQs), non-tradable output controls (IFQs), and certain input controls (Days-at-Sea).  We also do some other cool stuff.--->

Even without an ecological linkage (predator-prey or competition), a single species model of $F$ with implementation error lead to very different recommendations compared to a multispecies simulation model.


<!---
The implementation error approach is quite common.

This is a common approach(Irwin et al 2008). 
(Rosenberg and Brault 1993 Rosenberg, A.A. and Brault, S. (1993) Choosing a man-
agement strategy for stock rebuilding when control is
uncertain. Canadian Special Publication of Fisheries and
Aquatic Sciences 120, 243–253.

O’Boyle 1993  O’Boyle, R. (1993) Fisheries management organizations: a
study in uncertainty. Canadian Special Publication of
Fisheries and Aquatic Sciences 120, 423–436.

FAO 1996  FAO (1996) Precautionary approach to fisheries Part 2:
scientific papers prepared for the technical consultation
on the precautionary approach to capture fisheries
(including species introductions) Lysekil, Sweden, 6–13
June 1995. FAO Fish Tech Paper 350(Part 2). FAO,
Rome. p. 210.

 Francis and Shotton rancis, R.I.C.C. and Shotton, R. (1997) ‘‘Risk’’ in fisheries
management: a review. Canadian Journal of Fisheries and
Aquatic Sciences 54, 1699–1715.

Dichemont 2006abc papers.
 -->
 
 
## Groundfish Fishery 


We're going to need stylized facts about the groundfish fishery


## Related Literature
<!---We're not actually going to have a related literature section -->

Construction of complex simulation models with many sources of uncertainty is standard in the fisheries literature [c.f. @Smith1999; @Punt2016]. 
Our model is similar to that of @Ono2018, which models three principal groundfish stocks (Pacific Cod, Alaska Pollock, and Yellowfin Sole) and one bycatch species (Pacific Halibut).
Fishing vessels are assigned to metiers and assigned a baseline catch level based on historical data.  
The fishery manager *selects* total allowable catch for each metier-species combination. 
SSB will scale the baseline catch. 
It's unclear how/why the fishery stops fishing. 
But it's also quasi-behavioral, there's an "adjustment" to the scaling that accounts for adaptation.

Here is a partial list of single-species or independent models applied to  a fishery with techincal interactions (joint).

@Forrest2018 examines Hecate Strait Pacific Cod and Rock Sole.  The Rock sole stock assessment notes:

> Substantial reductions in the Pacific Cod (Gadus macrocephalus) TAC, starting with the 2000/2001 fishing season, likely affected Rock Sole catch patterns, as Rock Sole are often caught concurrently with Pacific Cod.  In Area 5CD, the reduction in Pacific Cod TAC was from 1000 tonnes to 200 tonnes within a single year (2000/2001).  Pacific Cod TACs have risen in recent years and are now at 1,200 tonnes in Area 5CDE and 590 tonnes in Area 5AB

@Sun2019 examines Gulf of Maine Atlantic Cod.  These are caught with other groundfish [@Squires1987;@Scheld2018] 

@Needle2008 examines North Sea haddock.
These are also caught with other groundfish.
@Amar2009 and @Ianelli2011 examine Gulf of Alaska Walleye Pollock. 
These are also caught with other groundfish [@Ono2018].

@Prellozo2016 examine the multispecies fishery in the Bay of Biscay.  
A metier-stock approach is taken: each metier has it's own catchability coefficient estimated from Increasing Returns to Scale production fucntion 
$$
h=qE^\alpha X^\beta
$$
where $\alpha=\beta=1$. 
@Prellozo2016 builds upon @Ulrich2011's FCUBE, which in turn, builds up on @Kell2007's FLR.

@Thorpe2017a; @Thorpe2019; @Thorpe2019a examines a multispecies fishery using a metier based approach.

