





#####   ---------------------------------- ########################

## ---
## output:
##   html_document: default
##   word_document: default
##   pdf_document: default
## ---

## ```{r, echo=FALSE, results='hide'}
## # Install the necessary functions
## ffiles <- list.files(path='documentation/stockRecruit/functions', 
##                      full.names=TRUE, recursive=TRUE)
## invisible(sapply(ffiles, source))

## # Read in the data. The appropriate stock will be selected below in the model function.
## recT <- read.csv(file='documentation/stockRecruit/data/recT.csv', 
##                  header=TRUE)
## ```

## # Analysis of Cod stock-recruit data (Beverton-Holt)

## ## Cod model parameters
## The relevant values that will be passed to the modeling function are:

## * stock: which stock are we working with
## * start: starting values for each parameter
## * lb: lower bounds for each parameter
## * ub: upper bounds for each parameter
## * estPar: 0/1 indicator for which parameters to estimate
## ```{r, echo = FALSE}

## # Parameters for the cod model
## codPar <- list(recDat = recT,
##                stock = 'GBCOD',
##             
##                start = c(log_a = -1.021315,
##                          log_b = 1,
##                          c = 2,
##                          log_sigR = log(0.1)),
##             
##                lb = c(log_a = -10,
##                       log_b = -10,
##                       c = -10,
##                       log_sigR = -10),
            
##                ub = c(log_a = 20,
##                       log_b = 20,
##                       c = 10,
##                       log_sigR = log(10)),
##                
##                # Parameters to estimate should have values of 1, parameters to
##                # fix at starting value should have value of 0
##                estPar = c(log_a = 1, 
##                           log_b = 1, 
##                           c = 1, 
##                           log_sigR = 1))

## parTab <- as.data.frame(round(do.call(cbind, codPar[3:6]), 2))
## parTab$stock <- codPar$stock
## print(parTab)

## ```



## ```{r, echo = FALSE, results = 'hide'}
## # Run the model -- 
## # The function do.call() just tells R to run the model code using the 
## # parameters provided in the parameter list.
## rep <- do.call(srRun, codPar)
## ```

## ## Results

## ### Model estimates

## #### Parameter estimates (on arithmetic scale)
## ```{r, echo=FALSE}
## estTab <- cbind(rep$sdrep$value, rep$sdrep$sd)
## colnames(estTab) <- c('Estimate', 'SE')
## print(estTab)
## ```

## #### Model-scale parameters & standard errors
## ```{r, echo=FALSE}
## estModTab <- cbind(rep$sdrep$par.fixed,
##                    sqrt(diag(rep$sdrep$cov.fixed)))
## colnames(estModTab) <- c('Estimate', 'SE')
## print(estModTab)
## ```

## #### Variance-covariance matrix (on model scale)
## ```{r, echo=FALSE}
## print(rep$sdrep$cov.fixed)
## ```

## ### S/R model fit
## #### Model fit with data assuming *median* temperature anomaly (`r round(median(rep$TANOM), 2) `) over the years that the data were fit

## ```{r, echo=FALSE}
## plotBH(rep)
## ```

## #### Model fit over multiple arbitrary temperature anomalies
## ```{r, echo=FALSE}
## plotBH(rep, varyT = TRUE)
## ```

## ### Model diagnostics

## #### Gradients for model components
## The gradients for each of the parameters is given below. Ideally they should all be small -- something on the order of 1x10^-5^. Certainly not larger than 1x10^-2^.
## ```{r, echo=FALSE}
## pnames <- names(rep$lb)
## mch <- match(names(rep$sdrep$par.fixed), pnames)
## grads <- c(rep$sdrep$gradient.fixed)
## names(grads) <- pnames[mch]
## print(grads)
## ```

## #### Starting values, estimates & bounds
## The parameters should not be near the bounds specified by  **lb** and **ub** in the table at the beginning of this document. Nor should the parameter estimates be exactly at their starting points. The plot below shows the parameter values relative to these bounds as well as the starting values and estimates. The starting values for each parameter are represented by an open circle while the estimates are the red filled circles. The parameter bounds are represented by the lines. If any parameter was not estimated (i.e., in the table at the beginning of this document the value for **estPar** is 0) then the starting value and estimate will coincide and the bound lines will appear as blue and dotted.

## ```{r, echo=FALSE}
## plotParEstBds(rep)
## ```







